name: Build and Publish

on:
  push:
    tags:
      - '*'  # Triggers on any tag
    branches:
      - '*'  # Triggers on any commit to any branch


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Angular CLI
        run: npm install -g @angular/cli@12.2.18 --no-progress

      - name: Install dependencies
        run: npm i -f

      - name: Build Library
        run: |
          npm run build-lib
          cd dist/collection-editor-library
          npm run prepublishOnly || true
          rm -f node_modules package-lock.json

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/collection-editor-library
          npm publish --access=public