name: Build and Publish

on:
  push:
    tags:
      - '*'  # Triggers on any tag
    branches:
      - '*'  # Triggers on any commit to any branch

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Show Node version
        run: node --version

      - name: Install Angular CLI
        run: npm install -g @angular/cli@12.2.18 --no-progress

      - name: Install dependencies
        run: npm i -f

      - name: Build and Pack Library
        run: |
          npm run build-lib
          npm pack ./dist/collection-editor-library

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm run build-lib
          PACKAGE_TGZ=$(npm pack ./dist/collection-editor-library)
          npm publish "$PACKAGE_TGZ" --access=public