name: Code Quality Checks

on:
  push:
    tags:
      - '*'

jobs:
  code-quality:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          cache: 'npm'

      - name: Using Angular CLI via npx
        run: npx @angular/cli@16 version

      - name: Install dependencies
        run: npm install --no-progress

      - name: Building
        run: mkdir -p /tmp/logs && npm run build-lib:prod | tee /tmp/logs/build.log
        
      - name: Executing test cases
        run: npm run test-coverage | tee /tmp/logs/test_cases.log
      